using System.Security.Cryptography;
using System.Text;
using System;

namespace TOTLP.Net
{
    /// <summary>
    /// A stateless, cross-platform generator for Time-based One-Time Linux Passwords (TOTLP).
    /// </summary>
    /// <remarks>
    /// This utility uses HMAC-SHA512 and a deterministic PRNG to produce highly secure, 
    /// rotating ASCII passwords that remain completely consistent across different operating systems and .NET runtimes.
    /// </remarks>
    public static class Totlp
    {
        // Standard RFC 4648 Base32 alphabet used for token encoding/decoding.
        private static readonly string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

        /// <summary>
        /// Generates a cryptographically secure Base32 secret key.
        /// This key acts as the master seed for subsequent password generation.
        /// </summary>
        /// <param name="length">The length of the token to generate.</param>
        /// <returns>A secure random Base32 string, or an empty string if length is less than or equal to zero.</returns>
        /// <example>
        /// <code>
        /// string masterKey = Totlp.GenerateToken(16);
        /// // Store this key securely in your database or configuration.
        /// </code>
        /// </example>
        public static string GenerateToken(int length)
        {
            if (length <= 0) return string.Empty;

            var sb = new StringBuilder(length);
            byte[] randomBytes = new byte[length];

            using (var rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(randomBytes);
            }

            // Modulo bias is mathematically zero here because 256 (byte values) is perfectly divisible by 32 (alphabet length).
            for (var i = 0; i < length; i++)
            {
                sb.Append(alphabet[randomBytes[i] % alphabet.Length]);
            }

            return sb.ToString();
        }

        /// <summary>
        /// Computes the active password for the current time period using the provided secret key.
        /// </summary>
        /// <param name="base32Secret">The Base32 encoded master key previously generated by <see cref="GenerateToken"/>.</param>
        /// <param name="length">The required length of the output password.</param>
        /// <returns>A complex ASCII password valid for the current hour.</returns>
        /// <exception cref="ArgumentNullException">Thrown if the provided secret is null or empty.</exception>
        /// <example>
        /// <code>
        /// string currentPassword = Totlp.GenerateCode("JBSWY3DPEHPK3PXP", 24);
        /// // Output: A complex string like "dl)=Q`qOnT4htcDJC{EaM_"
        /// </code>
        /// </example>
        public static string GenerateCode(string base32Secret, int length)
        {
            return InternalGenerateCode(base32Secret, length, DateTimeOffset.UtcNow.ToUnixTimeSeconds());
        }

        /// <summary>
        /// Computes a historical password for a past time window offset by a specified number of seconds.
        /// </summary>
        /// <param name="base32Secret">The Base32 encoded master key previously generated by <see cref="GenerateToken"/>.</param>
        /// <param name="length">The required length of the output password.</param>
        /// <param name="secondsBack">The number of seconds to subtract from the current Unix timestamp.</param>
        /// <returns>A complex ASCII password valid for the requested historical window.</returns>
        /// <exception cref="ArgumentNullException">Thrown if the provided secret is null or empty.</exception>
        /// <example>
        /// <code>
        /// string previousPassword = Totlp.GeneratePreviousCode("JBSWY3DPEHPK3PXP", 24, 3600);
        /// </code>
        /// </example>
        public static string GeneratePreviousCode(string base32Secret, int length, int secondsBack)
        {
            return InternalGenerateCode(base32Secret, length, DateTimeOffset.UtcNow.ToUnixTimeSeconds() - secondsBack);
        }

        /// <summary>
        /// Core execution engine that derives a deterministic ASCII password from a time-step and secret key.
        /// </summary>
        /// <param name="base32Secret">The input master secret key.</param>
        /// <param name="length">Target length of the final string output.</param>
        /// <param name="seconds">The specific Unix timestamp anchor to compute against.</param>
        /// <returns>The calculated pseudo-random string sequence.</returns>
        private static string InternalGenerateCode(string base32Secret, int length, long seconds)
        {
            var secretKey = Base32Decode(base32Secret);

            // Define the time step interval (3600 seconds = 1 hour).
            var timeStep = seconds / 3600;

            var timeStepBytes = BitConverter.GetBytes(timeStep);
            if (BitConverter.IsLittleEndian)
            {
                Array.Reverse(timeStepBytes); // RFC standard enforcement for Big-Endian serialization
            }

            byte[] hash;
            using (var hmac = new HMACSHA512(secretKey))
            {
                hash = hmac.ComputeHash(timeStepBytes);
            }

            // Dynamic truncation bitmask (0x3C = 60). Ensures the 4-byte extraction window 
            // never exceeds index 63, safely utilizing the entire 64-byte SHA-512 buffer.
            var offset = hash[hash.Length - 1] & 0x3C;
            var binaryCode = ((hash[offset] & 0x7F) << 24)
                           | ((hash[offset + 1] & 0xFF) << 16)
                           | ((hash[offset + 2] & 0xFF) << 8)
                           | (hash[offset + 3] & 0xFF);

            // Seed the deterministic PRNG with the extracted entropy.
            var rnd = new TotlpRandom(unchecked((uint)binaryCode));
            var sb = new StringBuilder(length);

            // Generate printable ASCII characters within the standard POSIX visible spectrum: 33 (!) to 126 (~).
            for (var i = 0; i < length; i++)
            {
                sb.Append(Convert.ToChar(rnd.Next(33, 127)));
            }

            return sb.ToString();
        }

        /// <summary>
        /// Decodes an RFC 4648 Base32 encoded string into its raw byte array representation.
        /// </summary>
        /// <param name="base32">The Base32 string to decode.</param>
        /// <returns>A byte array containing the decoded binary data, or an empty array if the input is null or invalid.</returns>
        private static byte[] Base32Decode(string base32)
        {
            if (string.IsNullOrEmpty(base32)) return Array.Empty<byte>();

            base32 = base32.TrimEnd('=').ToUpper();

            byte[] returnArray = new byte[base32.Length * 5 / 8];
            byte returnArrayPosition = 0;
            int bitOffset = 0;
            int currentByte = 0;

            foreach (char c in base32)
            {
                int value = alphabet.IndexOf(c);
                if (value < 0) continue;

                currentByte = (currentByte << 5) | value;
                bitOffset += 5;

                if (bitOffset >= 8)
                {
                    bitOffset -= 8;
                    returnArray[returnArrayPosition++] = (byte)(currentByte >> bitOffset);
                }
            }

            return returnArray;
        }

        /// <summary>
        /// A deterministic Linear Congruential Generator (LCG).
        /// Guarantees identical output sequences across all .NET runtimes and operating systems.
        /// </summary>
        private class TotlpRandom
        {
            private uint _state;

            public TotlpRandom(uint seed)
            {
                _state = seed;
            }

            /// <summary>
            /// Advances the internal LCG state and returns the next pseudo-random integer.
            /// </summary>
            public int Next()
            {
                _state = (_state * 1103515245) + 12345;
                return (int)(_state & 0x7FFFFFFF);
            }

            /// <summary>
            /// Returns a deterministic pseudo-random integer within the specified range.
            /// </summary>
            /// <param name="min">The inclusive lower bound.</param>
            /// <param name="max">The exclusive upper bound.</param>
            /// <exception cref="ArgumentOutOfRangeException">Thrown if <paramref name="min"/> is greater than or equal to <paramref name="max"/>.</exception>
            public int Next(int min, int max)
            {
                if (min >= max)
                    throw new ArgumentOutOfRangeException(nameof(min), "Minimum value must be less than maximum value.");

                int range = max - min;
                return min + (Next() % range);
            }
        }
    }
}