name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore signing key
      env:
        SIGNING_KEY: ${{ secrets.VS_SIGNING_KEY }}
      run: |
        if [ ! -z "$SIGNING_KEY" ]; then
          echo $SIGNING_KEY | base64 --decode > TOTLP.Net/Totlp.snk
        fi

    - name: Restore dependencies
      run: dotnet restore TOTLP.Net/TOTLP.Net.csproj
      
    - name: Build and pack project
      run: dotnet build TOTLP.Net/TOTLP.Net.csproj --no-restore --configuration Release
      
    - name: Publish to NuGet.org
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push TOTLP.Net/bin/Release/**/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Upload assets to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          TOTLP.Net/bin/Release/**/*.nupkg
          TOTLP.Net/bin/Release/netstandard2.0/TOTLP.Net.dll
